apiVersion: v1
kind: Service
metadata:
  name: coursework2
  namespace: coursework2
spec:
  selector:
    app: coursework2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
