- name: restart Azure VM
  hosts: localhost

  vars:
    myResourceGroup: kubernetes
    myVM: ansible-node

  tasks:
    - name: Restart virtual machine
      azure_rm_virtualmachine:
        resource_group: "{{ myResourceGroup }}"
        name: "{{ myVM }}"
        restarted: yes
