apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-coursework
  namespace: devops-coursework
spec:
  replicas: 4
  selector:
    matchLabels:
      app: coursework2
  template:
    metadata:
      labels:
        app: coursework2
    spec:
      containers:
        - name: coursework2
          image: docker.io/wenbeir/coursework2:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
