apiVersion: apps/v1
kind: Deployment
metadata:
  name: coursework2
  labels:
    app: web
spec:
  replicas: 4
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: docker.io/wenbeir/coursework2:latest
        ports:
        - containerPort: 8080

