sudo apt-get update

wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -

sudo apt install -y virtualbox

curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64

chmod +x minikube

sudo mv minikube /usr/local/bin/

minikube start --vm-driver=virtualbox
username@VM:~/ansible$ ^C
username@VM:~/ansible$ cat vm_confkubernetes.yml
- name: Configure Production VM
  hosts: azure
  user: azureuser
  become: yes

  vars:
    myResourceGroup: DevOps
    myVM: productionVM
  tasks:
  - name: Install Various Packages
    apt:
      update_cache: yes
      name: "{{ packages }}"
    vars:
      packages:
      - libssl-dev
      - libffi-dev
      - python-dev
      - python-pip

  - stat:
      path: /home/azureuser/kubernetes_install.sh
    register: kubernetesResult

  - stat:
      path: /home/azureuser/minikube_install.sh
    register: minikubeResult

  - name: Copy kubernetes_install.sh to productionVM
    copy:
      src: ./kubernetes_install.sh
      dest: /home/azureuser/kubernetes_install.sh
    when: kubernetesResult.stat.exists == false

  - name: Set kubernetes_install.sh permissions
    command: chmod +x /home/azureuser/kubernetes_install.sh

  - name: Run kubernetes installation script
    command: sudo /home/azureuser/kubernetes_install.sh

  - name: Copy minikube_install.sh to productionVM
    copy:
      src: ./minikube_install.sh
      dest: /home/azureuser/minikube_install.sh
    when: minikubeResult.stat.exists == false

  - name: Set minikube_install.sh permissions
    command: chmod +x /home/azureuser/minikube_install.sh

  - name: Run minikube installation script
    command: sudo /home/azureuser/minikube_install.sh
